# Array in R
---

Today, we will talk about the array. The array is very close to the matrix but can have more than two dimensions.  In other words, the matrix is a particular case of the array. 

We use `array()` function to create array.  The item in an array should be the same data type. 

Let's see an example of how to create an array.

In [1]:
# We created array by following form
array_example <- array(data = NA, dim = length(data), dimnames = NULL)

array_1 <- array(1:24, dim = c(2, 3, 4))

dnames1 <- c('A1', 'A2') 
dnames2 <- c('B1', 'B2', 'B3')
dnames3 <- c('C1', 'C2', 'C3', 'C4')

array_2 <- array(1:24, dim = c(2, 3, 4), dimnames = list(dnames1, dnames2, dnames3))

```R
> array_1
, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 4

     [,1] [,2] [,3]
[1,]   19   21   23
[2,]   20   22   24
```

This array is a basic one, we could find R provides us name for each matrix even we do not set names when we create the array.

```R
> array_2
, , C1

   B1 B2 B3
A1  1  3  5
A2  2  4  6

, , C2

   B1 B2 B3
A1  7  9 11
A2  8 10 12

, , C3

   B1 B2 B3
A1 13 15 17
A2 14 16 18

, , C4

   B1 B2 B3
A1 19 21 23
A2 20 22 24
```

For this array, we set name for each dimension. 

We could use `dim()` to check array's shape and use `aperm()` to transpose array. 

To subsetting array, we could use position to select subset or use names if we set names when we created an array. 


In [2]:
# Use position to select
array_2[, , 1]

B1 B2 B3
A1 1  3  5 
A2 2  4  6

In [3]:
# Use name to select
array_2[, , 'C1']

B1 B2 B3
A1 1  3  5 
A2 2  4  6

In [4]:
# Nothing is new, the operation is as same as matrix's operation
array_2[1, ,1]

B1 B2 B3 
 1  3  5

We finish today's tutorial if we consider matrix is a particular case of an array, so nothing is new today. Next time we will discuss data frame and factor.

See you next time!